#version: '3.8'
services:
  db:
    image: postgres:14
    env_file:
      - backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      # copie le SQL d'initialisation
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5433"

  backend:
    build: ./backend
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
