#version: '3.8'

services:
  db:
    image: postgres:14
    env_file: backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    env_file: backend/.env
    volumes:
      - ./backend/staticfiles/:/app/staticfiles/
    ports:
      - "8001:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .                   # <-- contexte = racine du projet
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
